using System.Collections.Generic;

namespace NgestorAdministrator.View.NetHome
{
    class DATA
    {
        public Dictionary<string, string> Operadora()
        {
            Dictionary<string, string> data = new Dictionary<string, string>();
            data.Add("netisp_06294", "ALMIRANTE TAMANDARE");
            data.Add("netsul_07458", "ALVORADA");
            data.Add("netabc_05386", "AMERICANA");
            data.Add("netabc_05389", "AMPARO");
            data.Add("netsorocaba_00178", "ANANINDEUA");
            data.Add("netbrasil_18511", "ANAPOLIS");
            data.Add("netsorocaba_05399", "APARECIDA");
            data.Add("netisp_08895", "APARECIDA DE GOIANIA");
            data.Add("netsul_06322", "APUCARANA");
            data.Add("netisp_02550", "ARACAJU");
            data.Add("netabc_05404", "ARACATUBA");
            data.Add("netabc_05405", "ARACOIABA DA SERRA");
            data.Add("netisp_03455", "ARAGUARI");
            data.Add("netsul_53902", "ARAPONGAS");
            data.Add("netabc_05409", "ARARAQUARA");
            data.Add("netabc_05413", "ARARAS");
            data.Add("netisp_06333", "ARAUCARIA");
            data.Add("netabc_05116", "ARMACAO DOS BUZIOS");
            data.Add("netisp_05419", "ARTUR NOGUEIRA");
            data.Add("netsul_05420", "ARUJA");
            data.Add("netabc_05423", "ATIBAIA");
            data.Add("netsul_66770", "BAGE");
            data.Add("netisp_07052", "BALNEARIO CAMBORIU");
            data.Add("netabc_05100", "BARRA MANSA");
            data.Add("netabc_05442", "BARRINHA");
            data.Add("netsorocaba_05443", "BARUERI");
            data.Add("netsul_05448", "BATATAIS");
            data.Add("netisp_05449", "BAURU");
            data.Add("netsorocaba_00194", "BELEM");
            data.Add("netsorocaba_05105", "BELFORD ROXO");
            data.Add("netbh_25666", "BELO HORIZONTE");
            data.Add("netsul_67040", "BENTO GONCALVES");
            data.Add("netabc_05456", "BERTIOGA");
            data.Add("netisp_03514", "BETIM");
            data.Add("netsul_07058", "BIGUACU");
            data.Add("netsul_75680", "BLUMENAU");
            data.Add("netsul_75681", "BLUMENAU BTV");
            data.Add("netabc_00156", "BOA VISTA");
            data.Add("netabc_05464", "BOITUVA");
            data.Add("netsorocaba_05471", "BOTUCATU");
            data.Add("netabc_05474", "BRAGANCA PAULISTA");
            data.Add("netbrasil_15890", "BRASILIA");
            data.Add("netisp_07070", "BRUSQUE");
            data.Add("netisp_01833", "CABEDELO");
            data.Add("netsul_05115", "CABO FRIO");
            data.Add("netabc_05487", "CACAPAVA");
            data.Add("netsorocaba_05488", "CACHOEIRA PAULISTA");
            data.Add("netsul_07560", "CACHOEIRINHA");
            data.Add("netisp_04911", "CACHOEIRO DE ITAPEMIRIM");
            data.Add("netsul_05498", "CAIEIRAS");
            data.Add("netisp_02750", "CAMACARI");
            data.Add("netsul_06379", "CAMBE");
            data.Add("netisp_01847", "CAMPINA GRANDE");
            data.Add("netisp_05509", "CAMPINAS");
            data.Add("netisp_07584", "CAMPO BOM");
            data.Add("netisp_08533", "CAMPO GRANDE");
            data.Add("netisp_06389", "CAMPO LARGO");
            data.Add("netisp_05129", "CAMPOS DOS GOYTACAZES");
            data.Add("netsul_07601", "CANELA");
            data.Add("netisp_07603", "CANOAS");
            data.Add("netsul_67784", "CAPAO DA CANOA");
            data.Add("netsorocaba_05530", "CAPIVARI");
            data.Add("netabc_05531", "CARAGUATATUBA");
            data.Add("netsorocaba_05533", "CARAPICUIBA");
            data.Add("netsul_07614", "CARAZINHO");
            data.Add("netisp_04917", "CARIACICA");
            data.Add("netisp_02152", "CARUARU");
            data.Add("netsorocaba_06413", "CASCAVEL");
            data.Add("netsul_00233", "CASTANHAL");
            data.Add("netsul_05543", "CATANDUVA");
            data.Add("netsul_68020", "CAXIAS DO SUL");
            data.Add("netsul_76066", "CHAPECO");
            data.Add("netsorocaba_06430", "CIANORTE");
            data.Add("netisp_06437", "COLOMBO");
            data.Add("netisp_03741", "CONSELHEIRO LAFAIETE");
            data.Add("netisp_03753", "CONTAGEM");
            data.Add("netsul_03778", "CORONEL FABRICIANO");
            data.Add("netisp_05565", "COSMOPOLIS");
            data.Add("netsorocaba_05567", "COTIA");
            data.Add("netabc_05569", "CRAVINHOS");
            data.Add("netsul_76180", "CRICIUMA");
            data.Add("netsul_68659", "CRUZ ALTA");
            data.Add("netsorocaba_05572", "CRUZEIRO");
            data.Add("netabc_05573", "CUBATAO");
            data.Add("netsorocaba_08719", "CUIABA");
            data.Add("netsul_55298", "CURITIBA - CABO");
            data.Add("netsul_55299", "CURITIBA - MMDS");
            data.Add("netabc_05576", "DESCALVADO");
            data.Add("netabc_05577", "DIADEMA");
            data.Add("netisp_03832", "DIVINOPOLIS");
            data.Add("netisp_08567", "DOURADOS");
            data.Add("netsul_05586", "DRACENA");
            data.Add("netsorocaba_05161", "DUQUE DE CAXIAS");
            data.Add("netsorocaba_05595", "ELIAS FAUSTO");
            data.Add("netsorocaba_05599", "EMBU DAS ARTES");
            data.Add("netsul_69019", "ERECHIM");
            data.Add("netisp_07757", "ESTANCIA VELHA");
            data.Add("netisp_07758", "ESTEIO");
            data.Add("netsul_69337", "FARROUPILHA");
            data.Add("netisp_02852", "FEIRA DE SANTANA");
            data.Add("netsul_76414", "FLORIANOPOLIS");
            data.Add("netsorocaba_01097", "FORTALEZA");
            data.Add("netsul_06506", "FOZ DO IGUACU");
            data.Add("netisp_05623", "FRANCA");
            data.Add("netisp_07154", "GASPAR");
            data.Add("netbrasil_19887", "GOIANIA");
            data.Add("netisp_03930", "GOVERNADOR VALADARES");
            data.Add("netsul_07817", "GRAMADO");
            data.Add("netisp_07820", "GRAVATAI");
            data.Add("netsul_07163", "GUARAMIRIM");
            data.Add("netsorocaba_06531", "GUARAPUAVA");
            data.Add("netsorocaba_05656", "GUARATINGUETA");
            data.Add("netabc_05659", "GUARUJA");
            data.Add("netsorocaba_05661", "GUARULHOS");
            data.Add("netabc_05668", "HORTOLANDIA");
            data.Add("netisp_05693", "INDAIATUBA");
            data.Add("netisp_04005", "IPATINGA");
            data.Add("netisp_07193", "ITAJAI");
            data.Add("netsul_04024", "ITAJUBA");
            data.Add("netabc_05712", "ITANHAEM");
            data.Add("netsorocaba_05714", "ITAPECERICA DA SERRA");
            data.Add("netisp_07194", "ITAPEMA");
            data.Add("netabc_05715", "ITAPETININGA");
            data.Add("netsorocaba_05722", "ITAPEVI");
            data.Add("netisp_05733", "ITAQUAQUECETUBA");
            data.Add("netsul_05739", "ITATIBA");
            data.Add("netabc_05746", "ITU");
            data.Add("netisp_04060", "ITUIUTABA");
            data.Add("netabc_05749", "ITUVERAVA");
            data.Add("netabc_02235", "JABOATAO DOS GUARARAPES");
            data.Add("netabc_05756", "JACAREI");
            data.Add("netabc_05761", "JAGUARIUNA");
            data.Add("netsorocaba_05765", "JANDIRA");
            data.Add("netsul_07203", "JARAGUA DO SUL");
            data.Add("netsorocaba_05769", "JAU");
            data.Add("netsorocaba_01907", "JOAO PESSOA");
            data.Add("netsul_77127", "JOINVILLE");
            data.Add("netisp_04126", "JUIZ DE FORA");
            data.Add("netisp_05776", "JUNDIAI");
            data.Add("netsul_07213", "LAGES");
            data.Add("netisp_04143", "LAGOA SANTA");
            data.Add("netsul_70408", "LAJEADO");
            data.Add("netsorocaba_03042", "LAURO DE FREITAS");
            data.Add("netabc_05791", "LIMEIRA");
            data.Add("netsul_56995", "LONDRINA");
            data.Add("netsorocaba_05795", "LORENA");
            data.Add("netsul_05798", "LOUVEIRA");
            data.Add("netabc_08756", "LUCAS DO RIO VERDE");
            data.Add("netisp_05197", "MACAE");
            data.Add("netsul_00393", "MACAPA");
            data.Add("netsorocaba_02480", "MACEIO");
            data.Add("netabc_05810", "MAIRINQUE");
            data.Add("netabc_00121", "MANAUS");
            data.Add("netsul_00272", "MARABA");
            data.Add("netsorocaba_05820", "MARILIA");
            data.Add("netsul_57304", "MARINGA");
            data.Add("netabc_05833", "MAUA");
            data.Add("netsorocaba_05239", "MESQUITA");
            data.Add("netabc_05850", "MIRASSOL");
            data.Add("netabc_05856", "MOGI DAS CRUZES");
            data.Add("netabc_05863", "MOGI GUACU");
            data.Add("netabc_05865", "MOGI MIRIM");
            data.Add("netabc_05869", "MONGAGUA");
            data.Add("netsorocaba_05882", "MONTE MOR");
            data.Add("netsul_07950", "MONTENEGRO");
            data.Add("netisp_04275", "MONTES CLAROS");
            data.Add("netsorocaba_01695", "NATAL");
            data.Add("netisp_07260", "NAVEGANTES");
            data.Add("netsorocaba_05226", "NILOPOLIS");
            data.Add("netbrasil_05228", "NITEROI");
            data.Add("netisp_05230", "NOVA FRIBURGO");
            data.Add("netsorocaba_05237", "NOVA IGUACU");
            data.Add("netisp_04312", "NOVA LIMA");
            data.Add("netsul_05910", "NOVA ODESSA");
            data.Add("netsul_71242", "NOVO HAMBURGO - CABO");
            data.Add("netsul_71243", "NOVO HAMBURGO - MMDS");
            data.Add("netabc_02269", "OLINDA");
            data.Add("netabc_05923", "ORLANDIA");
            data.Add("netsorocaba_05924", "OSASCO");
            data.Add("netisp_07278", "PALHOCA");
            data.Add("netisp_00540", "PALMAS");
            data.Add("netsul_06749", "PARANAGUA");
            data.Add("netsorocaba_01637", "PARNAMIRIM");
            data.Add("netsul_71587", "PASSO FUNDO");
            data.Add("netisp_05954", "PAULINIA");
            data.Add("netabc_02291", "PAULISTA");
            data.Add("netabc_05966", "PEDREIRA");
            data.Add("netsul_71706", "PELOTAS");
            data.Add("netabc_05972", "PERUIBE");
            data.Add("netisp_05250", "PETROPOLIS");
            data.Add("netabc_05976", "PINDAMONHANGABA");
            data.Add("netisp_06770", "PINHAIS");
            data.Add("netisp_05985", "PIRACICABA");
            data.Add("netisp_06009", "POA");
            data.Add("netsul_04437", "POCOS DE CALDAS");
            data.Add("netsorocaba_06794", "PONTA GROSSA");
            data.Add("netsul_71986", "PORTO ALEGRE - CABO");
            data.Add("netsul_71987", "PORTO ALEGRE - MMDS");
            data.Add("netsorocaba_06022", "PORTO FELIZ");
            data.Add("netisp_00022", "PORTO VELHO");
            data.Add("netsorocaba_06024", "POTIM");
            data.Add("netsul_04459", "POUSO ALEGRE");
            data.Add("netabc_06027", "PRAIA GRANDE");
            data.Add("netisp_06036", "PRESIDENTE PRUDENTE");
            data.Add("netsorocaba_06048", "RAFARD");
            data.Add("netabc_51136", "RECIFE");
            data.Add("netabc_05268", "RESENDE");
            data.Add("netisp_06067", "RIBEIRAO PIRES");
            data.Add("netisp_06070", "RIBEIRAO PRETO");
            data.Add("netisp_00066", "RIO BRANCO");
            data.Add("netabc_06076", "RIO CLARO");
            data.Add("netisp_05285", "RIO DAS OSTRAS");
            data.Add("netbrasil_63118", "RIO DE JANEIRO");
            data.Add("netsul_72451", "RIO GRANDE");
            data.Add("netsul_09112", "RIO VERDE");
            data.Add("netsul_06851", "ROLANDIA");
            data.Add("netisp_08818", "RONDONOPOLIS");
            data.Add("netisp_04541", "SABARA");
            data.Add("netsorocaba_06095", "SALTO");
            data.Add("netabc_06096", "SALTO DE PIRAPORA");
            data.Add("netsorocaba_03230", "SALVADOR");
            data.Add("netabc_06103", "SANTA BARBARA D OESTE");
            data.Add("netabc_06104", "SANTA BRANCA");
            data.Add("netabc_06108", "SANTA CRUZ DO RIO PARDO");
            data.Add("netsul_72842", "SANTA CRUZ DO SUL");
            data.Add("netsul_72907", "SANTA MARIA");
            data.Add("netsorocaba_06121", "SANTANA DE PARNAIBA");
            data.Add("netabc_06129", "SANTO ANDRE");
            data.Add("netbrasil_06139", "SANTOS");
            data.Add("netabc_89897", "SANTOS ABC");
            data.Add("netabc_06141", "SAO BERNARDO DO CAMPO");
            data.Add("netabc_06143", "SAO CAETANO DO SUL");
            data.Add("netisp_06144", "SAO CARLOS");
            data.Add("netisp_05305", "SAO GONCALO");
            data.Add("netsorocaba_05316", "SAO JOAO DE MERITI");
            data.Add("netabc_06154", "SAO JOAQUIM DA BARRA");
            data.Add("netisp_07363", "SAO JOSE");
            data.Add("netisp_06158", "SAO JOSE DO RIO PRETO");
            data.Add("netabc_06162", "SAO JOSE DOS CAMPOS");
            data.Add("netisp_06923", "SAO JOSE DOS PINHAIS");
            data.Add("netisp_89710", "SAO LEOPOLDO - CABO");
            data.Add("netsul_73466", "SAO LEOPOLDO - MMDS");
            data.Add("netsorocaba_00696", "SAO LUIS");
            data.Add("netsul_06171", "SAO MIGUEL ARCANJO");
            data.Add("netsp_88412", "SAO PAULO");
            data.Add("netsul_05320", "SAO PEDRO DA ALDEIA");
            data.Add("netsul_06178", "SAO ROQUE");
            data.Add("netabc_06182", "SAO SEBASTIAO");
            data.Add("netabc_06187", "SAO VICENTE");
            data.Add("netisp_08330", "SAPIRANGA");
            data.Add("netisp_08332", "SAPUCAIA DO SUL");
            data.Add("netisp_05066", "SERRA");
            data.Add("netabc_88579", "SERRA NEGRA");
            data.Add("netsorocaba_06195", "SERTAOZINHO");
            data.Add("netisp_04742", "SETE LAGOAS");
            data.Add("netsul_08837", "SINOP");
            data.Add("netsul_01521", "SOBRAL");
            data.Add("netsorocaba_06201", "SOROCABA");
            data.Add("netsul_08838", "SORRISO");
            data.Add("netabc_06207", "SUMARE");
            data.Add("netisp_06209", "SUZANO");
            data.Add("netsorocaba_06216", "TABOAO DA SERRA");
            data.Add("netsul_06233", "TATUI");
            data.Add("netabc_06235", "TAUBATE");
            data.Add("netisp_04763", "TEOFILO OTONI");
            data.Add("netsorocaba_00863", "TERESINA");
            data.Add("netisp_05338", "TERESOPOLIS");
            data.Add("netsorocaba_06241", "TIETE");
            data.Add("netabc_04770", "TIMOTEO");
            data.Add("netsul_08398", "TORRES");
            data.Add("netsul_06246", "TREMEMBE");
            data.Add("netsul_04780", "TRES CORACOES");
            data.Add("netabc_06261", "UBATUBA");
            data.Add("netisp_04803", "UBERABA");
            data.Add("netisp_04806", "UBERLANDIA");
            data.Add("netsul_74748", "URUGUAIANA");
            data.Add("netsorocaba_06272", "VALINHOS");
            data.Add("netsorocaba_06276", "VARGEM GRANDE PAULISTA");
            data.Add("netsul_04821", "VARGINHA");
            data.Add("netsorocaba_08858", "VARZEA GRANDE");
            data.Add("netsul_06277", "VARZEA PAULISTA");
            data.Add("netisp_04834", "VESPASIANO");
            data.Add("ctv_02121", "VIA EMBRATEL");
            data.Add("netsul_08471", "VIAMAO");
            data.Add("netsorocaba_05078", "VILA VELHA");
            data.Add("netsul_06279", "VINHEDO");
            data.Add("netsorocaba_05083", "VITORIA");
            data.Add("netisp_03363", "VITORIA DA CONQUISTA");
            data.Add("netisp_05359", "VOLTA REDONDA");
            data.Add("netsul_06282", "VOTORANTIM");
            data.Add("netsul_08493", "XANGRI-LA");

            return data;
        }
        public Dictionary<string, string> Operacao()
        {
            Dictionary<string, string> data = new Dictionary<string, string>();
            data.Add("218", "ALMIRANTE TAMANDARE");
            data.Add("342", "ALVORADA");
            data.Add("80", "AMERICANA");
            data.Add("438", "AMPARO");
            data.Add("158", "ANANINDEUA");
            data.Add("81", "ANAPOLIS");
            data.Add("159", "APARECIDA");
            data.Add("278", "APARECIDA DE GOIANIA");
            data.Add("343", "APUCARANA");
            data.Add("279", "ARACAJU");
            data.Add("1", "ARACATUBA");
            data.Add("439", "ARACOIABA DA SERRA");
            data.Add("238", "ARAGUARI");
            data.Add("2", "ARAPONGAS");
            data.Add("3", "ARARAQUARA");
            data.Add("4", "ARARAS");
            data.Add("239", "ARAUCARIA");
            data.Add("440", "ARMACAO DOS BUZIOS");
            data.Add("219", "ARTUR NOGUEIRA");
            data.Add("478", "ARUJA");
            data.Add("5", "ATIBAIA");
            data.Add("6", "BAGE");
            data.Add("240", "BALNEARIO CAMBORIU");
            data.Add("7", "BARRA MANSA");
            data.Add("441", "BARRINHA");
            data.Add("160", "BARUERI");
            data.Add("479", "BATATAIS");
            data.Add("8", "BAURU");
            data.Add("161", "BELEM");
            data.Add("162", "BELFORD ROXO");
            data.Add("9", "BELO HORIZONTE");
            data.Add("10", "BENTO GONCALVES");
            data.Add("11", "BERTIOGA");
            data.Add("220", "BETIM");
            data.Add("344", "BIGUACU");
            data.Add("12", "BLUMENAU");
            data.Add("84", "BLUMENAU BTV");
            data.Add("442", "BOA VISTA");
            data.Add("443", "BOITUVA");
            data.Add("86", "BOTUCATU");
            data.Add("13", "BRAGANCA PAULISTA");
            data.Add("14", "BRASILIA");
            data.Add("241", "BRUSQUE");
            data.Add("242", "CABEDELO");
            data.Add("345", "CABO FRIO");
            data.Add("15", "CACAPAVA");
            data.Add("163", "CACHOEIRA PAULISTA");
            data.Add("346", "CACHOEIRINHA");
            data.Add("378", "CACHOEIRO DE ITAPEMIRIM");
            data.Add("347", "CAIEIRAS");
            data.Add("280", "CAMACARI");
            data.Add("348", "CAMBE");
            data.Add("281", "CAMPINA GRANDE");
            data.Add("16", "CAMPINAS");
            data.Add("243", "CAMPO BOM");
            data.Add("17", "CAMPO GRANDE");
            data.Add("244", "CAMPO LARGO");
            data.Add("282", "CAMPOS DOS GOYTACAZES");
            data.Add("480", "CANELA");
            data.Add("245", "CANOAS");
            data.Add("85", "CAPAO DA CANOA");
            data.Add("164", "CAPIVARI");
            data.Add("444", "CARAGUATATUBA");
            data.Add("165", "CARAPICUIBA");
            data.Add("481", "CARAZINHO");
            data.Add("246", "CARIACICA");
            data.Add("283", "CARUARU");
            data.Add("93", "CASCAVEL");
            data.Add("482", "CASTANHAL");
            data.Add("349", "CATANDUVA");
            data.Add("18", "CAXIAS DO SUL");
            data.Add("19", "CHAPECO");
            data.Add("94", "CIANORTE");
            data.Add("221", "COLOMBO");
            data.Add("379", "CONSELHEIRO LAFAIETE");
            data.Add("247", "CONTAGEM");
            data.Add("483", "CORONEL FABRICIANO");
            data.Add("222", "COSMOPOLIS");
            data.Add("166", "COTIA");
            data.Add("445", "CRAVINHOS");
            data.Add("20", "CRICIUMA");
            data.Add("21", "CRUZ ALTA");
            data.Add("167", "CRUZEIRO");
            data.Add("22", "CUBATAO");
            data.Add("168", "CUIABA");
            data.Add("23", "CURITIBA - CABO");
            data.Add("24", "CURITIBA - MMDS");
            data.Add("446", "DESCALVADO");
            data.Add("25", "DIADEMA");
            data.Add("284", "DIVINOPOLIS");
            data.Add("380", "DOURADOS");
            data.Add("484", "DRACENA");
            data.Add("169", "DUQUE DE CAXIAS");
            data.Add("170", "ELIAS FAUSTO");
            data.Add("171", "EMBU DAS ARTES");
            data.Add("26", "ERECHIM");
            data.Add("248", "ESTANCIA VELHA");
            data.Add("285", "ESTEIO");
            data.Add("27", "FARROUPILHA");
            data.Add("286", "FEIRA DE SANTANA");
            data.Add("28", "FLORIANOPOLIS");
            data.Add("198", "FORTALEZA");
            data.Add("350", "FOZ DO IGUACU");
            data.Add("29", "FRANCA");
            data.Add("249", "GASPAR");
            data.Add("30", "GOIANIA");
            data.Add("287", "GOVERNADOR VALADARES");
            data.Add("485", "GRAMADO");
            data.Add("250", "GRAVATAI");
            data.Add("486", "GUARAMIRIM");
            data.Add("95", "GUARAPUAVA");
            data.Add("172", "GUARATINGUETA");
            data.Add("31", "GUARUJA");
            data.Add("87", "GUARULHOS");
            data.Add("32", "HORTOLANDIA");
            data.Add("33", "INDAIATUBA");
            data.Add("288", "IPATINGA");
            data.Add("289", "ITAJAI");
            data.Add("487", "ITAJUBA");
            data.Add("447", "ITANHAEM");
            data.Add("173", "ITAPECERICA DA SERRA");
            data.Add("381", "ITAPEMA");
            data.Add("34", "ITAPETININGA");
            data.Add("174", "ITAPEVI");
            data.Add("251", "ITAQUAQUECETUBA");
            data.Add("351", "ITATIBA");
            data.Add("35", "ITU");
            data.Add("382", "ITUIUTABA");
            data.Add("448", "ITUVERAVA");
            data.Add("138", "JABOATAO DOS GUARARAPES");
            data.Add("36", "JACAREI");
            data.Add("449", "JAGUARIUNA");
            data.Add("175", "JANDIRA");
            data.Add("352", "JARAGUA DO SUL");
            data.Add("88", "JAU");
            data.Add("96", "JOAO PESSOA");
            data.Add("37", "JOINVILLE");
            data.Add("290", "JUIZ DE FORA");
            data.Add("38", "JUNDIAI");
            data.Add("488", "LAGES");
            data.Add("252", "LAGOA SANTA");
            data.Add("39", "LAJEADO");
            data.Add("143", "LAURO DE FREITAS");
            data.Add("40", "LIMEIRA");
            data.Add("41", "LONDRINA");
            data.Add("176", "LORENA");
            data.Add("353", "LOUVEIRA");
            data.Add("450", "LUCAS DO RIO VERDE");
            data.Add("291", "MACAE");
            data.Add("489", "MACAPA");
            data.Add("97", "MACEIO");
            data.Add("451", "MAIRINQUE");
            data.Add("42", "MANAUS");
            data.Add("490", "MARABA");
            data.Add("89", "MARILIA");
            data.Add("43", "MARINGA");
            data.Add("44", "MAUA");
            data.Add("177", "MESQUITA");
            data.Add("452", "MIRASSOL");
            data.Add("45", "MOGI DAS CRUZES");
            data.Add("46", "MOGI GUACU");
            data.Add("47", "MOGI MIRIM");
            data.Add("453", "MONGAGUA");
            data.Add("178", "MONTE MOR");
            data.Add("491", "MONTENEGRO");
            data.Add("292", "MONTES CLAROS");
            data.Add("179", "NATAL");
            data.Add("383", "NAVEGANTES");
            data.Add("118", "NET SERVICOS");
            data.Add("180", "NILOPOLIS");
            data.Add("141", "NITEROI");
            data.Add("293", "NOVA FRIBURGO");
            data.Add("181", "NOVA IGUACU");
            data.Add("223", "NOVA LIMA");
            data.Add("354", "NOVA ODESSA");
            data.Add("48", "NOVO HAMBURGO - CABO");
            data.Add("49", "NOVO HAMBURGO - MMDS");
            data.Add("139", "OLINDA");
            data.Add("454", "ORLANDIA");
            data.Add("182", "OSASCO");
            data.Add("224", "PALHOCA");
            data.Add("225", "PALMAS");
            data.Add("492", "PARANAGUA");
            data.Add("183", "PARNAMIRIM");
            data.Add("50", "PASSO FUNDO");
            data.Add("226", "PAULINIA");
            data.Add("140", "PAULISTA");
            data.Add("455", "PEDREIRA");
            data.Add("51", "PELOTAS");
            data.Add("456", "PERUIBE");
            data.Add("294", "PETROPOLIS");
            data.Add("52", "PINDAMONHANGABA");
            data.Add("253", "PINHAIS");
            data.Add("53", "PIRACICABA");
            data.Add("227", "POA");
            data.Add("355", "POCOS DE CALDAS");
            data.Add("92", "PONTA GROSSA");
            data.Add("54", "PORTO ALEGRE - CABO");
            data.Add("55", "PORTO ALEGRE - MMDS");
            data.Add("184", "PORTO FELIZ");
            data.Add("295", "PORTO VELHO");
            data.Add("185", "POTIM");
            data.Add("356", "POUSO ALEGRE");
            data.Add("56", "PRAIA GRANDE");
            data.Add("296", "PRESIDENTE PRUDENTE");
            data.Add("186", "RAFARD");
            data.Add("57", "RECIFE");
            data.Add("58", "RESENDE");
            data.Add("228", "RIBEIRAO PIRES");
            data.Add("59", "RIBEIRAO PRETO");
            data.Add("254", "RIO BRANCO");
            data.Add("60", "RIO CLARO");
            data.Add("255", "RIO DAS OSTRAS");
            data.Add("61", "RIO DE JANEIRO");
            data.Add("62", "RIO GRANDE");
            data.Add("493", "RIO VERDE");
            data.Add("357", "ROLANDIA");
            data.Add("384", "RONDONOPOLIS");
            data.Add("256", "SABARA");
            data.Add("187", "SALTO");
            data.Add("457", "SALTO DE PIRAPORA");
            data.Add("142", "SALVADOR");
            data.Add("63", "SANTA BARBARA DO OESTE");
            data.Add("64", "SANTA BRANCA");
            data.Add("458", "SANTA CRUZ DO RIO PARDO");
            data.Add("65", "SANTA CRUZ DO SUL");
            data.Add("66", "SANTA MARIA");
            data.Add("188", "SANTANA DE PARNAIBA");
            data.Add("67", "SANTO ANDRE");
            data.Add("68", "SANTOS");
            data.Add("69", "SANTOS - ABC");
            data.Add("70", "SAO BERNARDO DO CAMPO");
            data.Add("71", "SAO CAETANO DO SUL");
            data.Add("72", "SAO CARLOS");
            data.Add("229", "SAO GONCALO");
            data.Add("189", "SAO JOAO DE MERITI");
            data.Add("459", "SAO JOAQUIM DA BARRA");
            data.Add("297", "SAO JOSE");
            data.Add("73", "SAO JOSE DO RIO PRETO");
            data.Add("74", "SAO JOSE DOS CAMPOS");
            data.Add("230", "SAO JOSE DOS PINHAIS");
            data.Add("83", "SAO LEOPOLDO");
            data.Add("257", "SAO LEOPOLDO - CABO");
            data.Add("190", "SAO LUIS");
            data.Add("494", "SAO MIGUEL ARCANJO");
            data.Add("75", "SAO PAULO");
            data.Add("495", "SAO PEDRO DA ALDEIA");
            data.Add("358", "SAO ROQUE");
            data.Add("460", "SAO SEBASTIAO");
            data.Add("76", "SAO VICENTE");
            data.Add("258", "SAPIRANGA");
            data.Add("231", "SAPUCAIA DO SUL");
            data.Add("298", "SERRA");
            data.Add("418", "SERRA NEGRA");
            data.Add("90", "SERTAOZINHO");
            data.Add("299", "SETE LAGOAS");
            data.Add("496", "SINOP");
            data.Add("497", "SOBRAL");
            data.Add("77", "SOROCABA");
            data.Add("498", "SORRISO");
            data.Add("78", "SUMARE");
            data.Add("300", "SUZANO");
            data.Add("191", "TABOAO DA SERRA");
            data.Add("499", "TATUI");
            data.Add("79", "TAUBATE");
            data.Add("385", "TEOFILO OTONI");
            data.Add("192", "TERESINA");
            data.Add("301", "TERESOPOLIS");
            data.Add("193", "TIETE");
            data.Add("461", "TIMOTEO");
            data.Add("500", "TORRES");
            data.Add("359", "TREMEMBE");
            data.Add("501", "TRES CORACOES");
            data.Add("462", "UBATUBA");
            data.Add("302", "UBERABA");
            data.Add("303", "UBERLANDIA");
            data.Add("82", "URUGUAIANA");
            data.Add("91", "VALINHOS");
            data.Add("194", "VARGEM GRANDE PAULISTA");
            data.Add("360", "VARGINHA");
            data.Add("195", "VARZEA GRANDE");
            data.Add("361", "VARZEA PAULISTA");
            data.Add("232", "VESPASIANO");
            data.Add("398", "VIA EMBRATEL");
            data.Add("362", "VIAMAO");
            data.Add("99", "VILA VELHA");
            data.Add("363", "VINHEDO");
            data.Add("98", "VITORIA");
            data.Add("304", "VITORIA DA CONQUISTA");
            data.Add("305", "VOLTA REDONDA");
            data.Add("364", "VOTORANTIM");
            data.Add("365", "XANGRI-LA");
            return data;
        }
        public Dictionary<string, string> Localizacao()
        {
            Dictionary<string, string> data = new Dictionary<string, string>();
            data.Add("2", "ALMOXARIFADO");
            data.Add("7", "ATP");
            data.Add("18", "BASE");
            data.Add("19", "CENTRO DE DISTRIBUICAO");
            data.Add("9", "CENTRO DE REPARO");
            data.Add("17", "CENTRO DE REVERSA");
            data.Add("8", "DESAPARECIDO");
            data.Add("15", "DISTRIBUIDOR");
            data.Add("5", "EMPREITEIRA");
            data.Add("14", "FORNECEDOR");
            data.Add("13", "LABORATORIO");
            data.Add("3", "MANUTENCAO");
            data.Add("16", "OPERADOR LOGISTICO");
            data.Add("4", "TECNICO");
            data.Add("1", "TRANSPORTADORA");
            data.Add("10", "USO INTERNO");
            return data;
        }
        public Dictionary<string, string> TipoFiltros()
        {
            Dictionary<string, string> data = new Dictionary<string, string>();
            data.Add("", "TODOS NET");
            data.Add("N","NET");
            data.Add("C","CLARO");
            data.Add("AMBAS", "AMBAS"); 
            return data;
        }
    }
}
